Add article to exclude pulling nosto packages from Magento repo
supercid/wiki-docs pull request #38
Opened 2021-10-12 15:41 UTC by olsi-qose

This article cover instructions on how to handle the following error:

````
- Root composer.json requires nosto/module-nostotagging 5.2.10, it is satisfiable by nosto/module-nostotagging[5.2.10] from composer repo (https://repo.packagist.org) but nosto/module-nostotagging[1.1.1, 1.2.0, 2.1.0, ..., 2.11.0, 3.0.2, 3.7.0, 3.8.5, 5.0.7, 5.2.3] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable.
````

2021-10-13 06:22 UTC, mridang commented on installing.md
> +In case you are pulling the dependencies from Magento's repository `repo.magento.com` and you encounter an error where the latest release is not present,
Missing linebreak.

2021-10-13 06:22 UTC, mridang commented on installing.md
> +```json
Add linebreak

2021-10-13 06:23 UTC, mridang commented
Wouldn't you ned to also amend the other places? 

* https://github.com/Nosto/wiki-docs/blob/Magento2/addons/cmp/installing.md
* https://github.com/Nosto/wiki-docs/blob/Magento2/addons/msi/installing.md

2021-10-13 06:24 UTC, mridang requested changes
Please amend all references across the wiki and unify thee language when it comes to installating via Composer

2021-10-15 10:13 UTC, olsi-qose commented
> Wouldn't you ned to also amend the other places?
> 
> * https://github.com/Nosto/wiki-docs/blob/Magento2/addons/cmp/installing.md
> * https://github.com/Nosto/wiki-docs/blob/Magento2/addons/msi/installing.md

No, it happens only on the main module because the other two are not in the marketplace and repository https://getcomposer.org/doc/articles/repository-priorities.md#canonical-repositories

2021-10-15 12:23 UTC, mridang approved these changes

2021-10-15 12:24 UTC, merged